version: '3.3'

services:
  db:
      container_name: db_container
      image: postgres
      environment:
        POSTGRES_USER: "myUser"
        POSTGRES_PASSWORD: "myPassword"
        POSTGRES_DB: test_db
        PGDATA: /var/lib/postgresql/data/pgdata

      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data/pgdata
#  worker:
#    container_name: python_worker
#    image: my_python
#    dockerfile: Dockerfile
#    volumes:
#      - py_files:/

#